### ISSUE TITLE
Litejet 24 receives first event but no more?

### ISSUE THREAD

**Issue by jmhunter** [joncar/pylitejet#11]
I have a LiteJet 24 (firmware V 05.20) and pylitejet seems to be so close to interfacing with it perfectly.. but I'm stuck on one point.

I've enabled 'third party carriage return' in the software, and also enabled 'Load RS232' so that any changes to loads are signalled via RS232.

Using pylitejet in monitor mode with debugging enabled, it successfully reads all loads no problem, and will receive _one_ event (whether this is a keypress or a light turning on/off), but no more after that.

Is it an artefact of my test environment? (I'm on a Mac running python3 locally) My target is to have this working in Home Assistant where it seemed to exhibit the same type of behaviour, hence I've tried local debugging next.

Some details:
```
python3 ./test.py --path socket://10.1.2.3:20108 -v monitor
[successfully reads all loads, buttons etc.. last one shown here]
DEBUG:pylitejet:WantToSendRecv "^K138"
DEBUG:pylitejet:SendRecv(S) "^K138"
DEBUG:pylitejet:SendRecv(W)
DEBUG:pylitejet:Read "3               " (16)
DEBUG:pylitejet:SendRecv(R) "3               "
Press any key to stop monitoring...DEBUG:pylitejet:Read "P004" (4)
DEBUG:pylitejet:Event "P004"
Switch KI/BACK Top R (4) pressed.
DEBUG:pylitejet:Read "R004" (4)
DEBUG:pylitejet:Event "R004"
Switch KI/BACK Top R (4) released.
DEBUG:pylitejet:Read "F006" (4)
DEBUG:pylitejet:Event "F006"
```

This shows a light switch being pressed and released (P004/R004), and the resultant load turning on (F006) - but I see no events at all after this.

I don't know much about async python which this seems to be using - is there an easy place in the code to hook into? I've tried some simple `_LOGGER.debug('Hello')` type debugging but not sure where to search next.

**Comment by joncar** [comment]
The fact that all of the name loading went through okay and it got three events okay is a pretty good sign for all of the communication working. I can't think of anything that'd be obviously broken at that point where subsequent events would stop working.

The F and N events are from older firmwares. Newer firmwares report load changes as ^K with an included load level. My original MCP used the older firmware and my current MCP had the newer firmware, so pylitejet supports both events. This should be fine.

Other than using \r instead of \n in the protocol, LiteJet's raw output is easy to read. Have you hooked up a raw socket client to see that events actually do keep flowing over the network? Maybe the problem is upstream of pylitejet somehow. On Windows I'd use Putty for that but I'm not sure of the best tool on Mac. That'd be the next debugging step I suggest.

If they are show there fine, then maybe try looking at `_reader_impl`. I notice it has one `except` in there that could be dropping with no debug output.

**Comment by jmhunter** [comment]
Thank you very much for the speedy reply!

Hooking up a raw socket client is a great idea, thank you. I've used 'nc' on my laptop and can see that the network stream does seem to have all the events. I've pasted in an example for reference (different button press and different load on/off, but same behaviour) showing the button press and corresponding load on/off events.
```
$ nc 10.1.2.3 20108 | od -c
0000000    P   0   8   6  \r   R   0   8   6  \r   F   0   2   4  \r   P
0000020    0   8   6  \r   R   0   8   6  \r   N   0   2   4  \r   P   0
0000040    8   6  \r   R   0   8   6  \r   F   0   2   4  \r   P   0   8
0000060    6  \r   R   0   8   6  \r   N   0   2   4  \r   P   0   8   6
0000100   \r   R   0   8   6  \r   F   0   2   4  \r   P   0   8   6  \r
0000120    R   0   8   6  \r   N   0   2   4  \r   P   0   8   6  \r   R
0000140    0   8   6  \r   F   0   2   4  \r   P   0   8   6  \r   R   0
```

I've confirmed that I get the same behaviour from pylitejet on a Mac laptop and on Ubuntu 22.04 desktop, so I don't think it's an environment issue (although always happy to be corrected!)

My steps to test:
```
git clone https://github.com/joncar/pylitejet && \
cd pylitejet && \
mkdir venv && \
python3 -m venv venv && \
source venv/bin/activate

python3 -m pip install pyserial
python3 ./test.py --path socket://10.1.2.3:20108 -v monitor
```

I've added various debugging outputs to _reader_impl and it seems that at least the following conditions aren't true in this instance:
- The `except` at the top does not get triggered - it evidently doesn't fail to read a line
- The `while` loop doesn't exit. An `else:` block added after the `while` doesn't get triggered

I'll keep poking around... (I'm not familiar with asyncio yet!)

**Comment by joncar** [comment]
Oh, I think I see the bug. I added support for the load event to include the level in the new-firmware load event, but the the old-firmware load event isn't including that parameter. But the test monitor is always expecting to get *a* level parameter of some kind. I suspect it is causing a mismatch that gets eaten up in asyncio and the error isn't making it out like you'd expect.

That'd mean the fix might be changing:
```
            elif len(line) == 4 and (line[0] == "F" or line[0] == "N"):
                self._notify_event(line)
```
into
```
            elif len(line) == 4 and (line[0] == "F" or line[0] == "N"):
                self._notify_event(line, None)
```

**Comment by jmhunter** [comment]
> Oh, I think I see the bug. I added support for the load event to include the level in the new-firmware load event, but the the old-firmware load event isn't including that parameter. But the test monitor is always expecting to get _a_ level parameter of some kind. I suspect it is causing a mismatch that gets eaten up in asyncio and the error isn't making it out like you'd expect.

I think you're exactly right - good spot!

> ```
>             elif len(line) == 4 and (line[0] == "F" or line[0] == "N"):
>                 self._notify_event(line, None)
> ```

This now works (using 'monitor' in test.py) - at least, it no longer gets stuck, and events do now continue to flow! Definitely that's the problem area.

I do notice that the lighting level is shown as "??%" which makes sense of course - example: `Load LOUNGE (16) activated to ??%.`

Tomorrow I'll try and patch the HA integration and see how that goes.  I wonder if for Home Assistant use we need to add a second call to query the level, if using old protocol; but that's perhaps a separate challenge.

I've also noticed (using 'monitor') that if I hold down a button to dim a light up or down, no event gets sent by the MCP as of course the light is already on.. That might be a limitation of the old firmware. (I wonder if anyone has newer firmware available in binary form and I could just burn it to an EEPROM.. hmmm)

**Comment by joncar** [comment]
The Home Assistant integration doesn't use the parameter and always re-queries. I added the level parameter on the library side with the intention of using it eventually but forgot about it. So this should end up being a library-only fix, which is good because the HA pull request process for those dependency-only updates is pretty quick and painless!

Yeah, that limitation is why they changed the event format I suspect. Honestly in practice it never bugged me. But that depends on what direction on the slippery slope of automation means you should automate everything you are with Home Assistant, I suppose. Most of my lights go on and off based on sensors or more rarely me controlling via web app, than by using wall controls!

I bet you can get a final EEPROM from https://www.dragontechinc.com/. They are the original creators of LiteJet and still provide support for the now-deprecated systems. They are who I bought my 2nd MCP from when a lightning strike fried my first one.

**Comment by jmhunter** [comment]
Great, thank you!

I'm currently in the murky world of learning about HAOS and its containerised model, trying to get ssh access to the right bit of HA so I can find wherever the pylitejet library is cached and manually patch it to test. So far no luck figuring out the HAOS part - I'm deep into the rabbit hole now - but tonight I'll continue and let you know the outcome. I am sure it will work, though, given the success using test.py monitor!

**Comment by jmhunter** [comment]
I can confirm that this fixes the issue - I now have the integration working! 🥳 🍾

Really grateful for your time creating the integration in the first place, and also for helping troubleshoot this one! I feel as though I am now entering the 21st century properly 😄 After being way ahead of the curve 20+ years ago by installing this great system, it's taken me until now to actually change from my clunky perl script that was running the system until now, and bring it into the world of modern automation - so thank you!

Presumably the next step is for a new version containing this fix to be pushed out, then others can benefit too (and I won't need to manually patch when upgrading, also)?

Thanks again :)

For anyone following along at home - here's what I did to test the fix:
- I had to enable port 22222 ssh into my HA instance - official docs here: https://developers.home-assistant.io/docs/operating-system/debugging/
- ssh into HA via this debug mechanism and attach to the `homeassistant` docker container via `docker exec -it homeassistant /bin/sh`
- Finally, edit `/usr/local/lib/python3.12/site-packages/pylitejet/__init__.py` with the above patch)

**Comment by joncar** [comment]
You're welcome. I'm always surprised when I run into someone with the system. For so long I thought I was the only person who still had one. But these days a new someone pops up a few times a year.

Yup, next the Home Assistant devs will need to approve the PR to accept the new pylitejet version: https://github.com/home-assistant/core/pull/127063. We are probably too late for the October release, but I expect it'll be in the November release.

I was also able to fix the fact that reader loop could just silently die and start dropping all events. I think that is the root cause of at least one other bug someone else reported where HA would randomly stop getting LiteJet events eventually. So goodness even for those of us with the newer EEPROMs.

**Comment by jmhunter** [comment]
That's brilliant - and it looks like we might have just got in to the October release, also. I'll be sure to test and confirm all's working as soon as I can!

Yes, this doesn't seem to have been an incredibly popular system - perhaps due to its age and the wiring required to run it - but I've at least found it to be highly reliable and have had the benefit of a 'smart home' many years before others. Thanks to this library (and the HA integration) we can now enjoy the other benefits of HA, also!

I'll no doubt learn more as I explore the system over the next few days/weeks, and may even reach out to Dragon Tech about EPROM updates - but for now, my usual wake-up lighting was successfully orchestrated via HA this morning rather than cron and crusty perl, so that's a definite success, thank you!
